coverage:
    status:
        project:
            default:
                target: 55
                paths: ['src']
        patch:
            default:
                target: 75
                paths: ['src']
