x-healthcheck: &healthcheck
    interval: 2s
    timeout: 3s
    retries: 5
    start_period: 2s

x-python-env: &python-env
    PYTHONUNBUFFERED: 1
    PYTHONIOENCODING: UTF-8

services:
    vlei-server:
        image: gleif/vlei
        environment:
            <<: *python-env
        command: vLEI-server -s ./schema/acdc -c ./samples/acdc/ -o ./samples/oobis/
        healthcheck:
            test: curl -f http://localhost:7723/oobi/EBfdlu8R27Fbx-ehrqwImnK-8Cm79sqbAQ4MmvEAYqao
            <<: *healthcheck
        ports:
            - 7723:7723

    keria:
        image: ${KERIA_IMAGE:-weboftrust/keria}:${KERIA_IMAGE_TAG:-0.2.0-dev5}
        environment:
            KERI_AGENT_CORS: 1
            KERIA_CURLS: http://keria:3902/
            KERIA_IURLS: http://witness-demo:5642/oobi/BBilc4-L3tFUnfM_wJr4S4OJanAv_VmF_dJNN6vkf2Ha/controller;http://witness-demo:5643/oobi/BLskRTInXnMxWaGqcpSyMgo0nYbalW99cGZESrz3zapM/controller;http://witness-demo:5644/oobi/BIKKuvBwpmDVA4Ds-EpL5bt9OqPzWPja2LigFYZN2YfX/controller
            <<: *python-env
        healthcheck:
            test: wget --spider http://keria:3902/spec.yaml
            <<: *healthcheck
        ports:
            - 3901:3901
            - 3902:3902
            - 3903:3903

    witness-demo:
        image: weboftrust/keri-witness-demo:1.1.0
        environment:
            <<: *python-env
        healthcheck:
            test: curl -f http://localhost:5642/oobi
            <<: *healthcheck
        volumes:
            - ./config/witness-demo:/keripy/scripts/keri/cf/main
        ports:
            - 5642:5642
            - 5643:5643
            - 5644:5644
