x-healthcheck: &healthcheck
    interval: 2s
    timeout: 3s
    retries: 5
    start_period: 2s

x-python-env: &python-env
    PYTHONUNBUFFERED: 1
    PYTHONIOENCODING: UTF-8

services:
    vlei-server:
        image: gleif/vlei:1.0.3
        environment:
            <<: *python-env
        command: vLEI-server -s /vLEI/schema -c /vLEI/credentials -o /vLEI/oobis
        healthcheck:
            test: curl -f http://localhost:7723/oobi/EBfdlu8R27Fbx-ehrqwImnK-8Cm79sqbAQ4MmvEAYqao
            <<: *healthcheck
        ports:
            - 7723:7723

    keria:
        image: ${KERIA_IMAGE:-weboftrust/keria}:${KERIA_IMAGE_TAG:-0.4.0}
        environment:
            KERI_AGENT_CORS: 1
            <<: *python-env
        volumes:
            - ./config/keria.json:/keria/config/keri/cf/keria.json
        command: start --config-dir /keria/config --config-file keria --name keria
        healthcheck:
            test: wget --spider http://keria:3902/spec.yaml
            <<: *healthcheck
        ports:
            - 3901:3901
            - 3902:3902
            - 3903:3903

    witness-demo:
        image: ${KERI_IMAGE:-weboftrust/keri}:${KERI_IMAGE_TAG:-1.2.13}
        environment:
            <<: *python-env
        command: witness demo
        healthcheck:
            test: wget --spider http://127.0.0.1:5642/oobi
            <<: *healthcheck
        volumes:
            - ./config/witness-demo:/keripy/scripts/keri/cf/main
        ports:
            - 5642:5642
            - 5643:5643
            - 5644:5644
