import { assert, describe, it } from 'vitest';
import { Matter } from '../../src/keri/core/matter.ts';
import {
    parse,
    type AttachmentNode,
    type Primitive,
} from '../../src/keri/core/parsing.ts';

/* CESR 1.1 post-quantum codes.
 *
 * The spec places all 33 post-quantum primitives in the four-character fixed
 * tables, because every one of them is large — the smallest signature is 666 B
 * and the largest 29,792 B — so a four-character code costs under half a
 * percent of the encoding. These tests check the table against arithmetic the
 * spec makes checkable, and then against real cryptography. */

const bytesOf = (s: string) => new TextEncoder().encode(s);

/** Every post-quantum code, with its full size and its lead size. */
const PQ: Array<[string, number, number]> = [
    ['1AAQ', 1200, 0], // FN-DSA-512 public verification key
    ['1AAR', 892, 0], // FN-DSA-512 signature
    ['1AAS', 3460, 0], // ML-DSA-87 public verification key
    ['1AAT', 4416, 0], // ML-DSA-65 signature
    ['1AAU', 68, 0], // SLH-DSA-SHA2-192s public verification key
    ['1AAV', 68, 0], // SLH-DSA-SHAKE-192s public verification key
    ['1AAW', 21636, 0], // SLH-DSA-SHA2-192s signature
    ['1AAX', 21636, 0], // SLH-DSA-SHAKE-192s signature
    ['1AAY', 68, 0], // Seed of SLH-DSA-SHA2-128s private key
    ['1AAZ', 68, 0], // Seed of SLH-DSA-SHAKE-128s private key
    ['1AAa', 100, 0], // Seed of SLH-DSA-SHA2-192s private key
    ['1AAb', 100, 0], // Seed of SLH-DSA-SHAKE-192s private key
    ['1AAc', 132, 0], // Seed of SLH-DSA-SHA2-256s private key
    ['1AAd', 132, 0], // Seed of SLH-DSA-SHAKE-256s private key
    ['2AAA', 2396, 1], // FN-DSA-1024 public verification key
    ['2AAB', 1712, 1], // FN-DSA-1024 signature
    ['2AAC', 48, 1], // Seed of FN-DSA-512 private key
    ['2AAD', 48, 1], // Seed of FN-DSA-1024 private key
    ['2AAE', 2608, 1], // ML-DSA-65 public verification key
    ['2AAF', 3232, 1], // ML-DSA-44 signature
    ['2AAG', 48, 1], // Seed of ML-DSA-44 private key
    ['2AAH', 48, 1], // Seed of ML-DSA-65 private key
    ['2AAI', 48, 1], // Seed of ML-DSA-87 private key
    ['2AAJ', 48, 1], // SLH-DSA-SHA2-128s public verification key
    ['2AAK', 48, 1], // SLH-DSA-SHAKE-128s public verification key
    ['2AAL', 10480, 1], // SLH-DSA-SHA2-128s signature
    ['2AAM', 10480, 1], // SLH-DSA-SHAKE-128s signature
    ['2AAN', 39728, 1], // SLH-DSA-SHA2-256s signature
    ['2AAO', 39728, 1], // SLH-DSA-SHAKE-256s signature
    ['3AAA', 1756, 2], // ML-DSA-44 public verification key
    ['3AAB', 6176, 2], // ML-DSA-87 signature
    ['3AAC', 92, 2], // SLH-DSA-SHA2-256s public verification key
    ['3AAD', 92, 2], // SLH-DSA-SHAKE-256s public verification key
];

/** Every node in an attachment forest, groups and primitives alike. */
const nodes = (n: AttachmentNode): AttachmentNode[] =>
    n.kind === 'group' ? [n, ...n.items.flatMap(nodes)] : [n];

/** A CESR-1 stream: an Ed25519 inception, then a receipt of it whose witness
 * signs with post-quantum Falcon. Generated by cesrview's
 * scripts/make-falcon-sample.mjs from @noble/post-quantum — the FN-DSA-512
 * keypair is real and the signature is over the receipted event's exact bytes,
 * so it verifies. signify-ts cannot check that here (it ships no Falcon
 * implementation), but it can FRAME it, which is what these codes are for. */
const FALCON_RECEIPT =
    '{"v":"KERI10JSON0000fd_","t":"icp","d":"ECkqcQR_6_BzwC89QNM4OJnSwi3FDC62lo9ALKobHDe8","i":"BDVHH3ix0_aawmzCf-IBLdRe2UiFGCxEdXFuiecqyLEy","s":"0","kt":"1","k":["BDVHH3ix0_aawmzCf-IBLdRe2UiFGCxEdXFuiecqyLEy"],"nt":"0","n":[],"bt":"0","b":[],"c":[],"a":[]}{"v":"KERI10JSON000091_","t":"rct","d":"ECkqcQR_6_BzwC89QNM4OJnSwi3FDC62lo9ALKobHDe8","i":"BDVHH3ix0_aawmzCf-IBLdRe2UiFGCxEdXFuiecqyLEy","s":"0"}-CAB1AAQCQSYetAzLotj4VXDBKrzaYHHEePl0m4ROnIUpZCmhBUqSwcAuCQ7ObSuo6dOAlvHlt0DBNV1W9ezH8IDsofPULNgODfTaC2nXshKig_TF0FgkNKtewjtXZYWGk9fhhVj7lRPU7K_4P0XXRKEr9G_aIGNxUfy-S7STVqfR_rtgaEcSNjaIaMdGQkVQ5otRbL-AYphFxFM-ShV3vsUCCsbnJjxJ-oPe9bLvwZe0XMjDRF97LMUUOK7n7pVWDsXRq8lpogxRBR6NtUZ3NkblHxZM21pCHQ69yE_YysmzlEIhkbKr1WSuD5q5odkCaRvF0EPrCg34gLaUXKLW5Lva7MctqDbWSWj1Zwn_28tP0EoxQPszjPAuINKQvwkaKp6H6NvaozuOoQqehkMPYthDQsFakmWL2ceEoVdRjpmaq99SvANg5kMWGDx0udbcTka4-nbp6G6mNklljMARFZFPIfqAY1v1PUNX5JOpvq4of-uvI6H1wVVsB6dMmjZK0hVTFJCFE6JDOi7_QizhGkgNmShZyA9MZSrCMYVcY77VqsMp34kKc5HTg4-A4n8hjtnOmtV8igzhQ4pFrllDH49ELKJx0apnD4F1uUGTm0Iay3FwLmwAZpsUC8_LJfwgNzwREkISrrPDA3c6SvRTbcK5TbnLJ6vFSb4Y7ICMB0-ulDHg6o6_YK1SJnVudZYgDOd9KJJBSIA0L-OPgBbV8PLlx3MuRRdlnV6CmUHIzK-YM0ZKxs-aPZwCNiDlSCtmXoDZTd2TOlhT6p6HtWe1K3s0TLqkXGj6G1swasDw4fQAGFLMIOlDllxgUekz_xBNOjSxdC6pKhgEcpY8Z8G62LrhuV3ag1bEe6bNrb9qRse7nLaKMPr24g4_uCFqcJpu-HwFsnE7l4GiwgcRyVLcvS1OsjgDaGM9hvkimLWP1m_VEAzxlmzpko6uWz8ielfj0rmU8C7wp0fOJLRhRNkBbbD1e_ThkB9rIg8bDd8LesSO9bNEEhos5WCgiRhEvJyg7UTpWGGjQjXlWyigBTPO485RrmIbfWoCGX7Zmj5JNyYcLBIUqchWjnYTxB5XiWihkF7gwlCqRilP3UsNVefxY6mTmG310r5WPSYK3AeBX8prBeP3uixVdN07RVLNUjWluVPMZbRGYI95R2Jid5ZN0GagoiQUDoJIhAIhhVgaNEjOl0Zc41-1AAROX0FWKNW_m3Y1iRbg9hwfgdSjN10_hXmf58brBxXVClJ-mGCCfkAFHpN1KBKr0kYYR4ufwEKcTUO2PLftOwyVpawJONU5J6fjmY8GRopOpKVTRfzrsveMCvudZhMfMrjRMVl4XL8YgG4jCCRdsWkSF58ig6txHRUJU8lNyEEElPHUBiUbhzd9rDoFbeR1kqal3KK_C5W3ZounAx5zeZRKzlykYf2Uu8xDNuFe3e_mbQguld_m000cp01T0raLvQZLzpqciI5mZqbVu5mcNrU4Yz-SU0jJt7FxdlKbuXxRdVHwRB5NH2oY4kbD5EodFTyt-OrpEvFj23JbtMmS4GpNflrsw-ier5urUd5GkyIF4iAIlLk7c7Nmc3eEj2FJwKcurdKwShpoSe7d69EHZcampoR4lKPlctegPdXUv2yN62Y69PFZS5TXQKahF16OI-DhzBaVJruom2ONgeUlqF-KZNgsNf7yWlGQa3aNvY8SOkw2GzZV_FF3p6aD86rdpv5U4e49r3NSu0S5DnwNx2GRzLHL3Dt58yKsqrN0qhzYQE3PdSdqukj5HCWwTZUnRVba-J5ShZnQKcp22fJG5O1pmWHkGOw_3zyXufPBNhkUyixaq1I5Db8mluq5HeocWscHQJHyRtBF1qt0aw7cOYh5uOK-NfzrJQBKCZaF2zh_525a2nxpuiUDMTSsWZGtmqMTkWtpS09rgUVD_hBDqPfW1Nj7PcEdSldB3myaFAfhOSQXiotG1rOEC8KqP1dG01uGKBLj9ZeI2NiLj3X5HtwNMTX2NR-uLtp9TWSS5AchhJBKWYffXMfAKiJyyx4pGRtbcy3Wig8eyIhnWgfKYVq61ECOmkTJrPS6aZVmhGFafQ29AAAAAAAAAAA';

describe('post-quantum codes — the table is arithmetically self-checking', () => {
    it('carries the 33 codes CESR 1.1 defines', () => {
        const present = PQ.filter(([code]) => Matter.Sizes.has(code));
        assert.equal(present.length, 33);
    });

    it('sizes every code consistently with its selector and CESR encoding', () => {
        for (const [code, fs, ls] of PQ) {
            const sizage = Matter.Sizes.get(code);
            assert.ok(sizage, `${code}: missing from Matter.Sizes`);
            assert.equal(sizage.hs, 4, `${code}: not a four-character code`);
            assert.equal(
                sizage.ss,
                0,
                `${code}: fixed codes carry no soft part`
            );
            assert.equal(sizage.fs, fs, `${code}: wrong full size`);
            // The selector fixes the lead size: '1' -> 0, '2' -> 1, '3' -> 2.
            assert.equal(
                sizage.ls,
                ls,
                `${code}: lead size wrong for selector`
            );
            assert.equal(
                fs % 4,
                0,
                `${code}: full size ${fs} is not a multiple of 4`
            );
            // Raw plus lead must fill whole 24-bit groups, or the value could not
            // be encoded without padding characters, which fixed-length
            // primitives never carry.
            assert.equal(
                (((fs - 4) * 3) / 4) % 3,
                0,
                `${code}: does not align on 24 bits`
            );
        }
    });

    it('round-trips a raw value of the implied length through Matter, at every code', () => {
        for (const [code, fs, ls] of PQ) {
            // Zeros, because a lead byte that is not zero is rejected on decode.
            const raw = new Uint8Array(((fs - 4) * 3) / 4 - ls);
            const m = new Matter({ raw, code });
            assert.equal(
                m.qb64.length,
                fs,
                `${code}: encoded to the wrong length`
            );
            assert.equal(
                m.code,
                code,
                `${code}: round-tripped to a different code`
            );
            assert.equal(
                new Matter({ qb64: m.qb64 }).raw.length,
                raw.length,
                `${code}: decoded to the wrong raw length`
            );
        }
    });

    it('sizes the Falcon codes to the FN-DSA parameter sets exactly', () => {
        // Independent ground truth: FIPS 206 and the Falcon submission, not the
        // CESR table this is checking.
        const raw = (code: string) => {
            const s = Matter.Sizes.get(code)!;
            return ((s.fs! - 4) * 3) / 4 - s.ls!;
        };
        assert.equal(raw('1AAQ'), 897); // FN-DSA-512 public key
        assert.equal(raw('1AAR'), 666); // FN-DSA-512 signature, the PADDED variant
        assert.equal(raw('2AAA'), 1793); // FN-DSA-1024 public key
        assert.equal(raw('2AAB'), 1280); // FN-DSA-1024 signature
    });

    it('gives 2AAA and 3AAA their CESR 1.1 meanings, replacing two dead placeholders', () => {
        // These rows previously held Sizage(4, 0, 8, 1) and Sizage(4, 0, 8, 2):
        // vestigial test placeholders from a keripy that no longer exists —
        // keripy has used 2___ and 3___ for that purpose at every version, and
        // nothing in this codebase referenced them. Pinned here because it is
        // the one change in this commit that alters an existing row.
        assert.equal(Matter.Sizes.get('2AAA')!.fs, 2396);
        assert.equal(Matter.Sizes.get('3AAA')!.fs, 1756);
    });
});

describe('post-quantum codes — parsing a real Falcon stream', () => {
    it('frames the exhibit end to end with nothing left over', () => {
        const bytes = bytesOf(FALCON_RECEIPT);
        const { messages, errors, consumed } = parse(bytes);
        assert.deepStrictEqual(errors, []);
        assert.equal(consumed, bytes.length); // delta 0
        assert.deepStrictEqual(
            messages.map((m) => m.ilk),
            ['icp', 'rct']
        );
    });

    it('decomposes the receipt into a Falcon key and a Falcon signature', () => {
        const { messages } = parse(bytesOf(FALCON_RECEIPT));
        const group = messages[1].attachments[0];
        assert.equal(group.code, '-C');
        assert.equal(group.state, 'known');
        const items = group.items as Primitive[];
        assert.deepStrictEqual(
            items.map((p) => p.code),
            ['1AAQ', '1AAR']
        );
        // Byte-exact: the couple tiles the group with no gap and no overhang.
        assert.equal(items[0].span.end - items[0].span.start, 1200);
        assert.equal(items[1].span.end - items[1].span.start, 892);
        assert.equal(items[0].span.start, group.span.start + 4); // past the -C header
        assert.equal(items[1].span.end, group.span.end);
    });

    it('never frames a post-quantum signature as an INDEXED signature', () => {
        // CESR 1.1 defines no indexed post-quantum code, so no post-quantum
        // primitive may ever resolve through the Indexer table. A comment would
        // not fail if someone later added one.
        const all = parse(bytesOf(FALCON_RECEIPT)).messages.flatMap((m) =>
            m.attachments.flatMap(nodes)
        );
        assert.deepStrictEqual(
            all.filter((n) => n.kind === 'primitive' && n.class === 'indexer'),
            []
        );
        // The same rule at the framing layer: a -A group's members are Indexer
        // primitives, so a post-quantum code there must not resolve, however
        // well it would resolve as Matter.
        const icp = FALCON_RECEIPT.slice(0, 253);
        const { errors } = parse(
            bytesOf(icp + '-AAB' + '1AAR' + 'A'.repeat(888))
        );
        assert.equal(errors[0].code, 'unframable-group');
    });

    it('reports a truncated post-quantum primitive as incomplete, not malformed', () => {
        const bytes = bytesOf(FALCON_RECEIPT);
        const { messages, errors } = parse(bytes.slice(0, bytes.length - 40));
        assert.equal(messages.length, 1); // the icp survives; the receipt waits
        assert.equal(errors[0].code, 'incomplete');
        assert.equal(errors[0].permanent, false);
    });
});
