name: "Feature request"
description: Feature request template
title: "Feature request: short description"
labels: ["feature request", "triage"]
body:
  - type: textarea
    id: desired-behavior
    attributes:
      label:  Feature request description/rationale
    validations:
      required: true
