name: CI
on:
  push:
    branches:
      - 'main'
      - 'development'
  pull_request:
  workflow_dispatch:
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '18.12.1'
          cache: 'yarn'

      - name: build
        run: |
          npm ci
          npm test
          npm run build
