name: Publish NPM

on:
  workflow_dispatch:
    inputs:
      dist-tag:
        type: choice
        options:
          - dev
          - latest
        default: dev
        description: NPM dist tag
jobs:
  publish:
    name: Publish NPM
    permissions:
      contents: read
      id-token: write
    environment: npm-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish package
        env:
          NPM_PUBLISH_TAG: ${{ inputs.dist-tag }}
          NPM_PACKAGE_SCOPE: ${{ vars.NPM_PACKAGE_SCOPE }}
          NPM_PUBLISH_PROVENANCE: 1
        run: ./publish.sh
